name: Sentry Reports (Daily & Weekly)

on:
  # ⏰ 스케줄 (GitHub Actions cron은 UTC 기준)
  schedule:
    # 월요일 09:00 KST == 00:00 UTC
    - cron: "0 0 * * 1"
    # 화~금 09:00 KST == 00:00 UTC
    - cron: "0 0 * * 2-5"
  # ▶️ 수동 실행 (플랫폼/리포트 종류 선택 가능)
  workflow_dispatch:
    inputs:
      which:
        description: "리포트 종류"
        type: choice
        default: both
        options: [weekly, daily, both]
        required: true
      platform:
        description: "플랫폼"
        type: choice
        default: both
        options: [android, ios, both]
        required: true

env:
  # 공통 org (Repository → Settings → Variables 에 설정)
  SENTRY_ORG_SLUG: ${{ vars.SENTRY_ORG_SLUG }}

jobs:
  weekly:
    name: Weekly (${{ matrix.platform }})
    # 스케줄(월요일) 또는 수동 실행일 때만 잡 실행
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [android, ios]
        include:
          - platform: android
            SENTRY_PROJECT_ID: ${{ vars.ANDROID_PROJECT_ID }}
            SENTRY_PROJECT_SLUG: ${{ vars.ANDROID_PROJECT_SLUG }}
            SENTRY_DASHBOARD_URL: ${{ vars.ANDROID_DASHBOARD_URL }}
            SENTRY_ENVIRONMENT: "Production" # 안드로이드만 사용
          - platform: ios
            SENTRY_PROJECT_ID: ${{ vars.IOS_PROJECT_ID }}
            SENTRY_PROJECT_SLUG: ${{ vars.IOS_PROJECT_SLUG }}
            SENTRY_DASHBOARD_URL: ${{ vars.IOS_DASHBOARD_URL }}
            SENTRY_ENVIRONMENT: ""           # iOS는 비움(또는 키 생략)

    steps:
      - name: Check schedule matches weekly
        if: github.event_name == 'schedule'
        run: |
          if [ "${{ github.event.schedule }}" != "0 0 * * 1" ]; then
            echo "Not a weekly schedule tick. Exiting."
            exit 78
          fi

      - name: Check dispatch filter for weekly
        if: github.event_name == 'workflow_dispatch'
        run: |
          WHICH="${{ github.event.inputs.which }}"
          PLATFORM="${{ github.event.inputs.platform }}"
          MATRIX="${{ matrix.platform }}"
          if [ "$WHICH" != "weekly" ] && [ "$WHICH" != "both" ]; then
            echo "Dispatch is not for weekly. Exiting."
            exit 78
          fi
          if [ "$PLATFORM" != "both" ] && [ "$PLATFORM" != "$MATRIX" ]; then
            echo "Dispatch platform filter excludes this matrix ($MATRIX). Exiting."
            exit 78
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run weekly report
        env:
          # secrets
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          # vars / matrix
          SENTRY_ORG_SLUG: ${{ env.SENTRY_ORG_SLUG }}
          SENTRY_PROJECT_ID: ${{ matrix.SENTRY_PROJECT_ID }}
          SENTRY_PROJECT_SLUG: ${{ matrix.SENTRY_PROJECT_SLUG }}
          SENTRY_DASHBOARD_URL: ${{ matrix.SENTRY_DASHBOARD_URL }}
          SENTRY_ENVIRONMENT: ${{ matrix.SENTRY_ENVIRONMENT }}
        run: python sentry_weekly_crash_report.py

  daily:
    name: Daily (${{ matrix.platform }})
    # 스케줄(화~금) 또는 수동 실행일 때만 잡 실행
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [android, ios]
        include:
          - platform: android
            SENTRY_PROJECT_ID: ${{ vars.ANDROID_PROJECT_ID }}
            SENTRY_PROJECT_SLUG: ${{ vars.ANDROID_PROJECT_SLUG }}
            SENTRY_DASHBOARD_URL: ${{ vars.ANDROID_DASHBOARD_URL }}
            SENTRY_ENVIRONMENT: "Production"
          - platform: ios
            SENTRY_PROJECT_ID: ${{ vars.IOS_PROJECT_ID }}
            SENTRY_PROJECT_SLUG: ${{ vars.IOS_PROJECT_SLUG }}
            SENTRY_DASHBOARD_URL: ${{ vars.IOS_DASHBOARD_URL }}
            SENTRY_ENVIRONMENT: ""

    steps:
      - name: Check schedule matches daily
        if: github.event_name == 'schedule'
        run: |
          if [ "${{ github.event.schedule }}" != "0 0 * * 2-5" ]; then
            echo "Not a daily schedule tick. Exiting."
            exit 78
          fi

      - name: Check dispatch filter for daily
        if: github.event_name == 'workflow_dispatch'
        run: |
          WHICH="${{ github.event.inputs.which }}"
          PLATFORM="${{ github.event.inputs.platform }}"
          MATRIX="${{ matrix.platform }}"
          if [ "$WHICH" != "daily" ] && [ "$WHICH" != "both" ]; then
            echo "Dispatch is not for daily. Exiting."
            exit 78
          fi
          if [ "$PLATFORM" != "both" ] && [ "$PLATFORM" != "$MATRIX" ]; then
            echo "Dispatch platform filter excludes this matrix ($MATRIX). Exiting."
            exit 78
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run daily report
        env:
          # secrets
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          # vars / matrix
          SENTRY_ORG_SLUG: ${{ env.SENTRY_ORG_SLUG }}
          SENTRY_PROJECT_ID: ${{ matrix.SENTRY_PROJECT_ID }}
          SENTRY_PROJECT_SLUG: ${{ matrix.SENTRY_PROJECT_SLUG }}
          SENTRY_DASHBOARD_URL: ${{ matrix.SENTRY_DASHBOARD_URL }}
          SENTRY_ENVIRONMENT: ${{ matrix.SENTRY_ENVIRONMENT }}
        run: python sentry_daily_crash_report.py